export const FETCHED_TOURNAMENTS = 'FETCHED_TOURNAMENTS';
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';
export const DELETE_TOURNAMENT = 'DELETE_TOURNAMENT';
export const ADD_REQUEST_ERROR = 'ADD_REQUEST_ERROR';